export const verses = [
  { "reference": "João 3:16", "text": "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna." },
  { "reference": "Jeremias 29:11", "text": "Porque sou eu que conheço os planos que tenho para vocês', diz o Senhor, 'planos de fazê-los prosperar e não de lhes causar dano, planos de dar-lhes esperança e um futuro." },
  { "reference": "Romanos 8:28", "text": "Sabemos que Deus age em todas as coisas para o bem daqueles que o amam, dos que foram chamados de acordo com o seu propósito." },
  { "reference": "Filipenses 4:13", "text": "Tudo posso naquele que me fortalece." },
  { "reference": "Salmos 23:1", "text": "O Senhor é o meu pastor; de nada terei falta." },
  { "reference": "Provérbios 3:5-6", "text": "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas." },
  { "reference": "Gênesis 1:1", "text": "No princípio, Deus criou os céus e a terra." },
  { "reference": "Romanos 12:2", "text": "Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente, para que sejam capazes de experimentar e comprovar a boa, agradável e perfeita vontade de Deus." },
  { "reference": "Isaías 40:31", "text": "Mas aqueles que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam." },
  { "reference": "Gálatas 5:22-23", "text": "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio. Contra essas coisas não há lei." },
  { "reference": "Mateus 6:33", "text": "Busquem, pois, em primeiro lugar o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas." },
  { "reference": "Hebreus 11:1", "text": "Ora, a fé é a certeza daquilo que esperamos e a prova das coisas que não vemos." },
  { "reference": "2 Timóteo 3:16", "text": "Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça." },
  { "reference": "Josué 1:9", "text": "Não fui eu que ordenei a você? Seja forte и corajoso! Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar." },
  { "reference": "1 Coríntios 10:13", "text": "Não sobreveio a vocês tentação que не fosse comum aos homens. E Deus é fiel; ele não permitirá que vocês sejam tentados além do que podem suportar. Mas, quando forem tentados, ele mesmo lhes providenciará um escape, para que o possam suportar." },
  { "reference": "Salmos 46:1", "text": "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade." },
  { "reference": "Efésios 2:8-9", "text": "Pois vocês são salvos pela graça, por meio da fé, e isto não vem de vocês, é dom de Deus; não por obras, para que ninguém se glorie." },
  { "reference": "Romanos 3:23", "text": "Pois todos pecaram e estão destituídos da glória de Deus." },
  { "reference": "Romanos 6:23", "text": "Pois o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor." },
  { "reference": "João 14:6", "text": "Respondeu Jesus: 'Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai, a não ser por mim.'" },
  { "reference": "Mateus 11:28-30", "text": "Venham a mim, todos os que estão cansados e sobrecarregados, e eu lhes darei descanso. Tomem sobre vocês o meu jugo e aprendam de mim, pois sou manso e humilde de coração, e vocês encontrarão descanso para as suas almas. Pois o meu jugo é suave e o meu fardo é leve." },
  { "reference": "Isaías 41:10", "text": "Por isso não tema, pois estou com você; не tenha medo, pois sou o seu Deus. Eu o fortalecerei e o ajudarei; eu o segurarei com a minha mão direita vitoriosa." },
  { "reference": "Salmos 37:4", "text": "Deleite-se no Senhor, e ele atenderá aos desejos do seu coração." },
  { "reference": "1 João 1:9", "text": "Se confessarmos os nossos pecados, ele é fiel e justo para perdoar os nossos pecados e nos purificar de toda injustiça." },
  { "reference": "Romanos 5:8", "text": "Mas Deus demonstra seu amor por nós: Cristo morreu em nosso favor quando ainda éramos pecadores." },
  { "reference": "Filipenses 4:6-7", "text": "Não andem ansiosos por coisa alguma, mas em tudo, pela oração e súplicas, e com ação de graças, apresentem seus pedidos a Deus. E a paz de Deus, que excede todo o entendimento, guardará o coração e a mente de vocês em Cristo Jesus." },
  { "reference": "2 Coríntios 5:17", "text": "Portanto, se alguém está em Cristo, é nova criação. As coisas antigas já passaram; eis que surgiram coisas novas!" },
  { "reference": "João 1:1", "text": "No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus." },
  { "reference": "Salmos 119:105", "text": "A tua palavra é lâmpada que ilumina os meus passos e luz que clareia o meu caminho." },
  { "reference": "Isaías 53:5", "text": "Mas ele foi transpassado por causa das nossas transgressões, foi esmagado por causa de nossas iniquidades; o castigo que nos trouxe paz estava sobre ele, e pelas suas feridas fomos curados." },
  { "reference": "Provérbios 1:7", "text": "O temor do Senhor é o princípio do conhecimento, mas os insensatos desprezam a sabedoria e a disciplina." },
  { "reference": "Mateus 28:19-20", "text": "Portanto, vão e façam discípulos de todas as nações, batizando-os em nome do Pai e do Filho e do Espírito Santo, ensinando-os a obedecer a tudo o que eu lhes ordenei. E eu estarei sempre com vocês, até o fim dos tempos." },
  { "reference": "Marcos 10:45", "text": "Pois nem mesmo o Filho do homem veio para ser servido, mas para servir e dar a sua vida em resgate por muitos." },
  { "reference": "João 10:10", "text": "O ladrão vem apenas para roubar, matar e destruir; eu vim para que tenham vida, e a tenham plenamente." },
  { "reference": "Atos 1:8", "text": "Mas receberão poder quando o Espírito Santo descer sobre vocês, e serão minhas testemunhas em Jerusalém, em toda a Judeia e Samaria, e até os confins da terra." },
  { "reference": "Romanos 10:9-10", "text": "Se você confessar com a sua boca que Jesus é Senhor e crer em seu coração que Deus o ressuscitou dentre os mortos, será salvo. Pois com o coração se crê para a justiça, e com a boca se confessa para a salvação." },
  { "reference": "Gálatas 2:20", "text": "Fui crucificado com Cristo. Assim, já não sou eu quem vive, mas Cristo vive em mim. A vida que agora vivo no corpo, vivo-a pela fé no filho de Deus, que me amou e se entregou por mim." },
  { "reference": "Efésios 6:11", "text": "Vistam toda a armadura de Deus, para poderem ficar firmes contra as ciladas do Diabo." },
  { "reference": "Hebreus 12:1-2", "text": "Portanto, também nós, uma vez que estamos rodeados por tão grande nuvem de testemunhas, livremo-nos de tudo o que nos atrapalha e do pecado que nos envolve, e corramos com perseverança a corrida que nos é proposta, tendo os olhos fitos em Jesus, autor e consumador da nossa fé." },
  { "reference": "Tiago 1:2-3", "text": "Meus irmãos, considerem motivo de grande alegria o fato de passarem por diversas provações, pois vocês sabem que a prova da sua fé produz perseverança." },
  { "reference": "1 Pedro 5:7", "text": "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês." },
  { "reference": "Apocalipse 3:20", "text": "Eis que estou à porta e bato. Se alguém ouvir a minha voz e abrir a porta, entrarei e cearei com ele, e ele comigo." },
  { "reference": "Salmos 1:1-2", "text": "Como é feliz aquele que не segue o conselho dos ímpios, não imita a conduta dos pecadores, nem se assenta na roda dos zombadores! Ao contrário, sua satisfação está na lei do Senhor, e nessa lei medita dia e noite." },
  { "reference": "Salmos 19:1", "text": "Os céus declaram a glória de Deus; o firmamento proclama a obra das suas mãos." },
  { "reference": "Salmos 51:10", "text": "Cria em mim um coração puro, ó Deus, e renova dentro de mim um espírito estável." },
  { "reference": "Salmos 139:14", "text": "Eu te louvo porque me fizeste de modo especial e admirável. Tuas obras são maravilhosas! Digo isso com convicção." },
  { "reference": "Provérbios 16:9", "text": "Em seu coração o homem planeja o seu caminho, mas o Senhor determina os seus passos." },
  { "reference": "Isaías 26:3", "text": "Tu, Senhor, guardarás em perfeita paz aquele cujo propósito está firme, porque em ti confia." },
  { "reference": "Isaías 55:8-9", "text": "Pois os meus pensamentos não são os pensamentos de vocês, nem os seus caminhos são os meus caminhos', declara o Senhor. 'Assim como os céus são mais altos do que a terra, também os meus caminhos são mais altos do que os seus caminhos e os meus pensamentos mais altos do que os seus pensamentos.'" },
  { "reference": "Lamentações 3:22-23", "text": "Graças ao grande amor do Senhor é que não somos consumidos, pois as suas misericórdias são inesgotáveis. Renovam-se cada manhã; grande é a sua fidelidade." },
  { "reference": "Miqueias 6:8", "text": "Ele mostrou a você, ó homem, o que é bom e o que o Senhor exige de você: pratique a justiça, ame a fidelidade e ande humildemente com o seu Deus." },
  { "reference": "Mateus 5:16", "text": "Assim brilhe a luz de vocês diante dos homens, para que vejam as suas boas obras e glorifiquem ao Pai de vocês, que está nos céus." },
  { "reference": "Mateus 22:37-39", "text": "Respondeu Jesus: 'Ame o Senhor, o seu Deus, de todo o seu coração, de toda a sua alma e de todo o seu entendimento'. Este é o primeiro e maior mandamento. E o segundo, semelhante a este, é: 'Ame o seu próximo como a si mesmo'." },
  { "reference": "Marcos 16:15", "text": "E disse-lhes: 'Vão pelo mundo todo e preguem o evangelho a todas as pessoas.'" },
  { "reference": "João 1:12", "text": "Contudo, aos que o receberam, aos que creram em seu nome, deu-lhes o direito de se tornarem filhos de Deus." },
  { "reference": "João 8:32", "text": "E conhecerão a verdade, e a verdade os libertará." },
  { "reference": "João 11:25", "text": "Disse-lhe Jesus: 'Eu sou a ressurreição e a vida. Aquele que crê em mim, ainda que morra, viverá.'" },
  { "reference": "Atos 4:12", "text": "Não há salvação em nenhum outro, pois, debaixo do céu não há nenhum outro nome dado aos homens pelo qual devamos ser salvos." },
  { "reference": "Romanos 1:16", "text": "Não me envergonho do evangelho, porque é o poder de Deus para a salvação de todo aquele que crê: primeiro do judeu, depois do grego." },
  { "reference": "1 Coríntios 6:19-20", "text": "Acaso não sabem que o corpo de vocês é santuário do Espírito Santo que habita em vocês, que lhes foi dado por Deus, e que vocês não são de si mesmos? Vocês foram comprados por alto preço. Portanto, glorifiquem a Deus com o seu próprio corpo." },
  { "reference": "1 Coríntios 13:4-7", "text": "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. Não maltrata, não procura seus interesses, não se ira facilmente, não guarda rancor. O amor não se alegra com a injustiça, mas se alegra com a verdade. Tudo sofre, tudo crê, tudo espera, tudo suporta." },
  { "reference": "2 Coríntios 12:9", "text": "Mas ele me disse: 'Minha graça é suficiente para você, pois o meu poder se aperfeiçoa na fraqueza'. Portanto, eu me gloriarei ainda mais alegremente em minhas fraquezas, para que o poder de Cristo repouse em mim." },
  { "reference": "Efésios 3:20", "text": "Àquele que é capaz de fazer infinitamente mais do que tudo o que pedimos ou pensamos, de acordo com o seu poder que atua em nós." },
  { "reference": "Filipenses 2:3-4", "text": "Nada façam por ambição egoísta ou por vaidade, mas humildemente considerem os outros superiores a si mesmos. Cada um cuide, não somente dos seus interesses, mas também dos interesses dos outros." },
  { "reference": "Colossenses 3:23", "text": "Tudo o que fizerem, façam de todo o coração, como para o Senhor, e não para os homens." },
  { "reference": "1 Tessalonicenses 5:16-18", "text": "Alegrem-se sempre. Orem continuamente. Dêem graças em todas as circunstâncias, pois esta é a vontade de Deus para vocês em Cristo Jesus." },
  { "reference": "Hebreus 4:12", "text": "Pois a palavra de Deus é viva e eficaz, e mais afiada que qualquer espada de dois gumes; ela penetra até o ponto de dividir alma e espírito, juntas e medulas, e julga os pensamentos e intenções do coração." },
  { "reference": "Hebreus 13:8", "text": "Jesus Cristo é o mesmo, ontem, hoje e para sempre." },
  { "reference": "Tiago 2:17", "text": "Assim também a fé, por si só, se não for acompanhada de obras, está morta." },
  { "reference": "1 Pedro 2:9", "text": "Vocês, porém, são geração eleita, sacerdócio real, nação santa, povo exclusivo de Deus, para anunciar as grandezas daquele que os chamou das trevas para a sua maravilhosa luz." },
  { "reference": "Apocalipse 21:4", "text": "Ele enxugará dos seus olhos toda lágrima. Não haverá mais morte, nem tristeza, nem choro, nem dor, pois a antiga ordem já passou." },
  { "reference": "Deuteronômio 6:5", "text": "Ame o Senhor, o seu Deus, de todo o seu coração, de toda a sua alma e de todas as suas forças." },
  { "reference": "Salmos 34:8", "text": "Provem, e vejam como o Senhor é bom. Como é feliz o homem que nele se refugia!" },
  { "reference": "Salmos 91:1-2", "text": "Aquele que habita no esconderijo do Altíssimo e descansa à sombra do Onipotente pode dizer ao Senhor: 'Tu és o meu refúgio e a minha fortaleza, o meu Deus, em quem confio'." },
  { "reference": "Provérbios 22:6", "text": "Instrua a criança segundo os objetivos que você tem para ela, e mesmo com o passar dos anos não se desviará deles." },
  { "reference": "Provérbios 27:17", "text": "Assim como o ferro afia o ferro, o homem afia o seu companheiro." },
  { "reference": "Eclesiastes 3:1", "text": "Para tudo há uma ocasião, e um tempo para cada propósito debaixo do céu." },
  { "reference": "Naum 1:7", "text": "O Senhor é bom, um refúgio em tempos de angústia. Ele protege os que nele confiam." },
  { "reference": "Habacuque 3:17-18", "text": "Mesmo não florescendo a figueira, e não havendo uvas nas videiras, mesmo falhando a safra de azeitonas, e não havendo produção de alimento nas lavouras, nem ovelhas no curral, nem bois nos estábulos, ainda assim eu exultarei no Senhor e me alegrarei no Deus da minha salvação." },
  { "reference": "Sofonias 3:17", "text": "O Senhor, o seu Deus, está em seu meio, poderoso para salvar. Ele se regozijará em você; com o seu amor a renovará, ele se regozijará em você com brados de alegria." },
  { "reference": "Mateus 7:7", "text": "Peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta lhes será aberta." },
  { "reference": "Marcos 9:23", "text": "Disse-lhe Jesus: 'Se você pode crer, tudo é possível àquele que crê'." },
  { "reference": "Lucas 1:37", "text": "Pois nada é impossível para Deus." },
  { "reference": "João 15:5", "text": "Eu sou a videira; vocês são os ramos. Se alguém permanecer em mim e eu nele, esse dará muito fruto; pois sem mim vocês не podem fazer coisa alguma." },
  { "reference": "Atos 2:38", "text": "Pedro respondeu: 'Arrependam-se, e cada um de vocês seja batizado em nome de Jesus Cristo para perdão dos seus pecados, e receberão o dom do Espírito Santo'." },
  { "reference": "Romanos 8:38-39", "text": "Pois estou convencido de que nem morte nem vida, nem anjos nem demônios, nem o presente nem o futuro, nem quaisquer poderes, nem altura nem profundidade, nem qualquer outra coisa на criação será capaz de nos separar do amor de Deus que está em Cristo Jesus, nosso Senhor." },
  { "reference": "1 Coríntios 15:58", "text": "Portanto, meus amados irmãos, mantenham-se firmes, e que nada os abale. Sejam sempre dedicados à obra do Senhor, pois vocês sabem que no Senhor o trabalho de vocês não será inútil." },
  { "reference": "2 Coríntios 4:16-18", "text": "Por isso não desanimamos. Embora exteriormente estejamos a desgastar-nos, interiormente estamos sendo renovados dia após dia, pois os nossos sofrimentos leves e momentâneos estão produzindo para nós uma glória eterna que pesa mais do que todos eles. Assim, fixamos os olhos, não naquilo que se vê, mas no que não se vê, pois o que se vê é transitório, mas o que não se vê é eterno." },
  { "reference": "Gálatas 6:9", "text": "E não nos cansemos de fazer o bem, pois no tempo próprio colheremos, se não desanimarmos." },
  { "reference": "Efésios 4:32", "text": "Sejam bondosos e compassivos uns para com os outros, perdoando-se mutuamente, assim como Deus os perdoou em Cristo." },
  { "reference": "Colossenses 3:1-2", "text": "Portanto, já que vocês ressuscitaram com Cristo, procurem as coisas que são do alto, onde Cristo está assentado à direita de Deus. Mantenham o pensamento nas coisas do alto, e não nas coisas terrenas." },
  { "reference": "1 Timóteo 4:12", "text": "Ninguém o despreze pelo fato de você ser jovem, mas seja um exemplo para os fiéis na palavra, no procedimento, no amor, na fé e na pureza." },
  { "reference": "Hebreus 10:24-25", "text": "E consideremos uns aos outros para nos incentivarmos ao amor e às boas obras. Não deixemos de reunir-nos como igreja, segundo o costume de alguns, mas procuremos encorajar-nos uns aos outros, ainda mais quando vocês veem que se aproxima o Dia." },
  { "reference": "Tiago 4:7", "text": "Portanto, submetam-se a Deus. Resistam ao Diabo, e ele fugirá de vocês." },
  { "reference": "1 João 4:7-8", "text": "Amados, amemos uns aos outros, pois o amor procede de Deus. Aquele que não ama não conhece a Deus, porque Deus é amor." },
  { "reference": "Apocalipse 1:8", "text": "'Eu sou o Alfa e o Ômega', diz o Senhor Deus, 'o que é, o que era e o que há de vir, o Todo-poderoso'." },
  { "reference": "Salmos 27:1", "text": "O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é o meu forte refúgio; de quem terei medo?" },
  { "reference": "Salmos 121:1-2", "text": "Levanto os meus olhos para os montes; de onde me vem o socorro? O meu socorro vem do Senhor, que fez os céus e a terra." },
  { "reference": "Provérbios 4:23", "text": "Acima de tudo, guarde o seu coração, pois dele depende todo o decurso da sua vida." },
  { "reference": "Eclesiastes 12:13", "text": "Agora que já se ouviu tudo, aqui está a conclusão: Tema a Deus e obedeça aos seus mandamentos, porque isso é o essencial para o homem." }
]
